apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elk-automation
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elk-automation
            image: khainguyendinh/elk-automation
          restartPolicy: Never